"""
Django settings for kohn project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Darwin
# Linux (capture images and envelopes)
PLATFORM = os.uname().sysname

DEFAULT_NAME = "kohn"
HOST_IP = "10.211.55.2"
VM_IP = "10.211.55.3"

if PLATFORM == "Linux":
    SERVICES_IP = VM_IP
    DB_IP = "localhost"
elif PLATFORM == "Darwin":
    SERVICES_IP = VM_IP
    DB_IP = SERVICES_IP

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@k-&ba0suds0cq1t64ezu$w1jocj+caq)25hhr4rr^%k3x^e^2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]  # ["127.0.0.1", "localhost"]


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'capture',
    'processing',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kohn.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ["templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kohn.wsgi.application'
ASGI_APPLICATION = "kohn.asgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': DEFAULT_NAME,                      
        'USER': DEFAULT_NAME,
        'PASSWORD': DEFAULT_NAME,
        'HOST': DB_IP,
        # 'PORT': 'db_port_number',
    }
}

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(SERVICES_IP, 6379)],
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# Kohn camera settings
NEGATIVE_CAMERA_NAME = "Sony ILCE-7RM3A (PC Control)"
# ILCE-7RM3A

# Image path
if PLATFORM == "Linux":
    KOHN_IMAGE_PATH = "/home/parallels/Projects/images"
elif PLATFORM == "Darwin":
    KOHN_IMAGE_PATH = "/Users/kohn/Projects/images"
else:
    raise Exception(f"Unknown platform {PLATFORM}")

KOHN_IMAGE_PATH_RAW = f"{KOHN_IMAGE_PATH}/raw"
KOHN_IMAGE_PATH_JPG = f"{KOHN_IMAGE_PATH}/jpg"


# Celery
CELERY_TIMEZONE = 'America/Chicago'
CELERY_BROKER_URL = f'redis://{DB_IP}:6379/0'
CELERY_RESULT_BACKEND = f'redis://{DB_IP}:6379/0'
# CELERY_CACHE_BACKEND = 'django-cache'
CELERY_RESULT_EXTENDED = True
CELERY_TASK_TRACK_STARTED = True
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

CELERY_TASK_ROUTES = {
    "capture.tasks.log_data": {"queue": "messages"},
    "capture.tasks.log_message": {"queue": "messages"},
}

DJANGO_ALLOW_ASYNC_UNSAFE=True